// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'firebase_options.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWb0KGmUGoKVGQrdiDeeyxavOZxvh6L9g',
    appId: '1:39135044761:web:c1a665beedd3092dc4c408',
    messagingSenderId: '39135044761',
    projectId: 'anavis-a2730',
    authDomain: 'anavis-a2730.firebaseapp.com',
    storageBucket: 'anavis-a2730.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt8Qg_67EIyRvA52576G-0r8xWhJeHcks',
    appId: '1:39135044761:android:0a520b70d409932ec4c408',
    messagingSenderId: '39135044761',
    projectId: 'anavis-a2730',
    storageBucket: 'anavis-a2730.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwX4wMpmTC4iG-AyF8hiyL_xlzckCAtUo',
    appId: '1:39135044761:ios:db641fbfc29bfbd4c4c408',
    messagingSenderId: '39135044761',
    projectId: 'anavis-a2730',
    storageBucket: 'anavis-a2730.firebasestorage.app',
    iosBundleId: 'com.example.anavis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwX4wMpmTC4iG-AyF8hiyL_xlzckCAtUo',
    appId: '1:39135044761:ios:db641fbfc29bfbd4c4c408',
    messagingSenderId: '39135044761',
    projectId: 'anavis-a2730',
    storageBucket: 'anavis-a2730.firebasestorage.app',
    iosBundleId: 'com.example.anavis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWb0KGmUGoKVGQrdiDeeyxavOZxvh6L9g',
    appId: '1:39135044761:web:d720847ba156e72cc4c408',
    messagingSenderId: '39135044761',
    projectId: 'anavis-a2730',
    authDomain: 'anavis-a2730.firebaseapp.com',
    storageBucket: 'anavis-a2730.firebasestorage.app',
  );
}
